// ─── VYAN Website Version Registry ───────────────────────────────────────────
// Add a new entry at the TOP of SITE_VERSIONS for every meaningful release.
// Update CURRENT_VERSION to match.
// Tag the git commit: git tag v<version> <hash> && git push origin v<version>

export interface VersionEntry {
  version: string      // e.g. '1.2'
  date: string         // YYYY-MM-DD
  title: string        // short release name
  summary: string      // one or two sentences
  changes: string[]    // bullet list of what changed
  gitHash: string      // first 7 chars of commit hash
  pages: string[]      // which pages / systems were touched
}

export const SITE_VERSIONS: VersionEntry[] = [
  {
    version: '3.9.3',
    date: '2026-08-03',
    title: 'Text Legibility Fix',
    summary: 'All dim text across the Vistara experience panel and 3D in-frame cards brought up to readable opacity.',
    changes: [
      'Tantra subtitle (e.g. "VYAN ṚTAM"): 0.36 → 0.72 opacity',
      'Tagline strip in experience panel: 0.30 → 0.82 opacity',
      'Coming-soon placeholder text: 0.26 → 0.80 opacity',
      'Description text in 3D focused card: 0.62 → 0.90 opacity',
      'Nav hint text at bottom: 0.22 → 0.50 opacity',
    ],
    gitHash: '4a5524e',
    pages: ['Vistara'],
  },
  {
    version: '3.9.2',
    date: '2026-08-03',
    title: 'Gradient Border Fix',
    summary: 'Fixed the animated gradient border on the floating experience panel — was hidden due to a z-index conflict with the glass fill.',
    changes: [
      'Removed isolation:isolate and z-index:-1 from panel ::before pseudo-element',
      'Added pointer-events:none so the border layer does not block panel interactions',
      'Gradient border now correctly animates across all four panel edges',
    ],
    gitHash: '46a3939',
    pages: ['Vistara'],
  },
  {
    version: '3.9.1',
    date: '2026-08-03',
    title: 'Footer Suppression Fix',
    summary: 'NebulaFooter is now hidden while the experience panel is open, preventing it from overlapping panel content.',
    changes: [
      'NebulaFooter fades out (opacity 0, pointer-events none) when experience panel opens',
      'Footer restores when panel closes or on unmount',
    ],
    gitHash: '3a715c5',
    pages: ['Vistara'],
  },
  {
    version: '3.9',
    date: '2026-08-03',
    title: 'Floating Panel — All-Side Border & Hover Lift',
    summary: 'Experience panel redesigned as a floating card inset from all screen edges, with an animated gradient border on all four sides and a cinematic hover lift effect.',
    changes: [
      'Panel floats 20px from top, bottom, and outer edge — no longer edge-to-edge',
      'Animated gradient border runs around all four sides of the floating panel',
      'Hover lift: panel rises 7px with deepened shadow on pointer devices (disabled on touch)',
      'Footer no longer conflicts — panel clears the footer zone naturally via bottom inset',
      'Mobile: panel centers with 14px insets from all sides, scales to fill available space',
      'Tablet: panel widens to 62vw for better content density',
      'Dim backdrop opacity reduced slightly to let 3D scene show through more clearly',
    ],
    gitHash: 'bd51113',
    pages: ['Vistara'],
  },
  {
    version: '3.8',
    date: '2026-08-02',
    title: 'Cinematic Side Panel',
    summary: 'Experience overlay redesigned as a dramatic cinematic side panel that slides in from the left or right depending on each gateway\'s position in the 3D scene.',
    changes: [
      'Experience panel slides in from left or right (based on gateway 3D pos[0] sign) with spring-curve animation',
      'Other side shows dimmed 3D scene through semi-transparent backdrop — click to close',
      'Animated gradient light travels along the inner edge of the panel',
      'Exit animation: panel slides back out, backdrop fades simultaneously',
      'Escape key closes the side panel with full closing animation',
      'Arrow keys and scroll blocked while panel is open',
      'Mobile: panel widens to 92vw on narrow screens',
    ],
    gitHash: '21dcafa',
    pages: ['Vistara'],
  },
  {
    version: '3.7',
    date: '2026-08-02',
    title: 'Ṛtam Live Integration',
    summary: 'VYAN ṚTAM live app wired into the Vistara experience panel.',
    changes: [
      'VYAN ṚTAM: appUrl set to https://rtam.vyanlabs.com — loads live in the experience overlay iframe',
    ],
    gitHash: '5d7a5b8',
    pages: ['Vistara'],
  },
  {
    version: '3.6.2',
    date: '2026-08-02',
    title: 'Quantum Grid — 3D panel hides behind experience overlay',
    summary: 'Focused product card now hides when the experience overlay opens, so the 3D scene shows through the glass panel cleanly.',
    changes: [
      'Html transform elements ignore DOM z-index — suppressed focused panel render when expOpen is true',
      '3D scene now visible translucently through the experience overlay as intended',
    ],
    gitHash: '57a5eeb',
    pages: ['Vistara'],
  },
  {
    version: '3.6.1',
    date: '2026-08-02',
    title: 'Quantum Grid — Fix invisible experience overlay',
    summary: 'Experience panel was invisible after CSS class rename. Restored proper opaque glass with backdrop-filter for the experience overlay.',
    changes: [
      'Added .qg-exp-glass: deep-blue gradient 88%→80% opacity + backdrop-filter blur(8px) saturate(120%)',
      'Experience overlay uses qg-panel for gradient border + qg-exp-glass for the panel fill',
    ],
    gitHash: 'f922d55',
    pages: ['Vistara'],
  },
  {
    version: '3.6',
    date: '2026-08-02',
    title: 'Quantum Grid — Restored 3D panels, border-only gradient',
    summary: 'Panel restored inside the 3D frame. Gradient border uses CSS mask-composite so the animated gradient shows only on the 3px border, not the panel fill.',
    changes: [
      'Panel back inside <Html transform> — sits inside the 3D wireframe as before',
      'CSS ::before pseudo-element + mask-composite:exclude: gradient travels only along the border edge',
      'Panel interior: rgba(4,8,48,0.18) transparent deep blue — 3D scene visible through it',
    ],
    gitHash: '1109c37',
    pages: ['Vistara'],
  },
  {
    version: '3.5',
    date: '2026-08-02',
    title: 'Quantum Grid — True Glass & Nav Lock',
    summary: 'Focused panel moved to DOM so Shunya-style backdrop-filter works correctly. Scrolling and swiping no longer changes the active square while the experience overlay is open.',
    changes: [
      'Focused panel is now a regular DOM overlay (not inside R3F Html transform), enabling backdrop-filter to composite against the canvas',
      'Glass recipe matches Shunya realm: dark-blue gradient 52%→28% opacity + blur(8px) saturate(120%)',
      'Wheel and touch nav blocked while experience overlay is open',
      'expIdRef tracks overlay state without stale closure issues',
    ],
    gitHash: 'a7f1977',
    pages: ['Vistara'],
  },
  {
    version: '3.4.1',
    date: '2026-08-02',
    title: 'Quantum Grid — Fix experience overlay purple bleed',
    summary: 'Removed backdrop-filter from the experience overlay which was compositing against the WebGL canvas and turning the entire screen bright purple.',
    changes: [
      'Experience overlay: removed backdrop-filter, replaced with solid rgba(0,2,12,0.90) dark background',
    ],
    gitHash: '5aab08d',
    pages: ['Vistara'],
  },
  {
    version: '3.4',
    date: '2026-08-02',
    title: 'Quantum Grid — True Glass & Vivid Gradient Border',
    summary: 'Fixed glass panel transparency so the 3D scene shows through; gradient border now visibly travels blue→violet; background labels dimmed.',
    changes: [
      'Panel background: rgba(4,8,32,0.28) — genuinely see-through, 3D wireframes visible behind it',
      'Removed non-functional backdrop-filter (does not composite against WebGL canvas)',
      'Border padding 1.5px → 3px with more vivid blue→violet→blue gradient at 3s speed',
      'Non-focused gateway labels: opacity 0.45 → 0.16 — far less intrusive',
      'Corner brackets: fade to 0.12 opacity when focused and coloured red, not blue',
    ],
    gitHash: 'cbeac35',
    pages: ['Vistara'],
  },
  {
    version: '3.3',
    date: '2026-08-02',
    title: 'Quantum Grid — Glass Panels & Experience Overlay',
    summary: 'Active frames now show transparent deep blue glass with animated blue→violet gradient border. Each panel shows the VYAN logo, product name, description, and an EXPERIENCE button that opens a full-screen glass overlay.',
    changes: [
      'Focused frames: glassmorphism panel with animated gradient border (blue→violet travelling animation)',
      'Panel content: VYAN logo-symbol, product name in #ff2a4a red with glow, tantra label, description text, EXPERIENCE button',
      'EXPERIENCE button opens full-screen glass overlay with iframe (appUrl) or coming-soon placeholder',
      'Overlay: gradient-bordered glass panel, header with logo + product name + close button, click-outside to dismiss',
      'Bottom strip dot indicators and tantra label switched to #ff2a4a brand red',
    ],
    gitHash: 'c607c2e',
    pages: ['Vistara'],
  },
  {
    version: '3.2',
    date: '2026-08-02',
    title: 'Quantum Grid — Touch Nav & Deep Blue',
    summary: 'Swipe-to-navigate on touchscreens and deep blue (#1a40ff) brand color across QuantumGrid.',
    changes: [
      'Touch swipe left/right navigates between frames (40px threshold, 700ms cooldown)',
      'Replaced brand red with deep blue (#1a40ff) on all QuantumGrid UI elements',
    ],
    gitHash: 'ac12ac5',
    pages: ['Vistara'],
  },
  {
    version: '3.1',
    date: '2026-08-02',
    title: 'Quantum Grid — Brand Typography',
    summary: 'Applied VYAN Shunyalekh typeface and #ff2a4a brand red across all QuantumGrid UI.',
    changes: [
      'All QuantumGrid text now uses var(--font-vyan) — VYAN Shunyalekh',
      'Gateway labels, product names, tantra names, nav arrows, back button, dot indicator all in #ff2a4a',
      'Corner L-brackets on major frames tinted brand red at low opacity',
    ],
    gitHash: 'fa7c6f4',
    pages: ['Vistara'],
  },
  {
    version: '3.0',
    date: '2026-08-02',
    title: 'Vistara — Quantum Grid',
    summary: 'Replaces the 3D orb system with a wireframe quantum grid: 9 VYAN gateways as interactive frames floating in deep 3D space with looping scroll/arrow navigation and camera fly-to.',
    changes: [
      'New QuantumGrid component — 80 background wireframe rects + nested pairs, 2200 dot particles, perspective floor grid',
      '9 major gateway frames (Ṛtam, Ojas, Mudrā, Netra, Ākṛti, Sūtra, Chitra-Prāṇa, Māyā, Saṅgraha) with corner brackets and accent colors',
      'Camera continuously drifts in spherical orbit, changing direction every 9–22 s',
      'Click-to-fly: easeInOutCubic arc to selected gateway (2.5 s), click again to release',
      'Looping navigation: scroll wheel, ‹ › buttons, arrow keys — last → first loops back',
      'Bottom strip: product tantra name, 9-dot progress indicator, hint text',
      'gateways.ts rewritten with quantum grid schema (pos, w, h, rotX, rotY); orb fields removed',
      'Deleted orphaned VistaraVoid scene components (GatewayOrbs, KnowledgeStreams, SacredGeometry, VistaraScene, VoidAtmosphere, CameraRig)',
      'Saṅgraha added as 9th gateway (tagline/description pending)',
    ],
    gitHash: 'b0f89ee',
    pages: ['Vistara', 'Gateways'],
  },
  {
    version: '2.9',
    date: '2026-07-22',
    title: 'Vistara — Panel UX + Icons + Sound + Rings + Header',
    summary: 'Five UX fixes: panel touch-scroll, clickable version/overview icons, sound console visible, Saturn-like ring particles, stark-red name + shimmer tagline in panel header.',
    changes: [
      'Panel scroll: pointer/touch stopPropagation on slab + preventDefault on scroll div',
      'Version badge and Overview button z-index raised to 9200 (above NebulaFooter 9100)',
      'SoundConsole z-index raised 25→8500 — panel now opens above canvas',
      'Saturn rings: 14000 particles/ring, 0.4–1.1px, hard step() disc (zero blur)',
      'Panel header orb name: stark red #e80010',
      'Panel tagline: deep-blue→purple gradient shimmer, alternating L↔R per orb',
    ],
    gitHash: 'd8490b5',
    pages: ['Vistara', 'All pages'],
  },
  {
    version: '2.8',
    date: '2026-07-22',
    title: 'Vistara — v1.9 Ring Shader Restored',
    summary: 'Stardust ring particles restored to v1.9 proportional sizing (2.2–7px, aSize-relative min/max). Proportional formula prevents the uniform-blob look caused by fixed pixel clamps.',
    changes: [
      'aSize 2.2–7px (v1.9 range restored)',
      'gl_PointSize: clamp(aSize*580/dist, aSize*1.1, aSize*2.5) — proportional min/max',
      'Fragment: disc smoothstep(0.05→0.88), disc*0.72 + sprk*0.55',
      'vAlpha density*(0.65 + uTilt*1.4) — brighter than v1.9 to compensate for no bloom',
      '5000 particles per ring',
    ],
    gitHash: 'e3eb8c0',
    pages: ['Vistara'],
  },
  {
    version: '2.7',
    date: '2026-07-22',
    title: 'Vistara — Rings Actually Visible',
    summary: 'Saturn stardust rings were invisible after glow-removal over-correction — 1px particles at 12% alpha. Rebuilt with 7000 particles per ring at 2.5–5px, 70% base alpha, and brighter fragment output.',
    changes: [
      'Particle count 3000→7000 per ring for continuous visible arc coverage',
      'Base aSize 0.8–1.8px→2.5–5px; gl_PointSize max 2.5→9px',
      'vAlpha base 0.48→0.70 — rings are always bright, density wave modulates ±15%',
      'Fragment output col*1.2 — clean stardust, no bloom, no halo',
    ],
    gitHash: '106d9cc',
    pages: ['Vistara'],
  },
  {
    version: '2.6',
    date: '2026-07-22',
    title: 'Vistara — Camera Arc Traversal',
    summary: 'When switching between focused orbs, the camera now arcs through the gyroscope scene: pulling back toward overview distance while panning to the new orb, then swooping back into close-up.',
    changes: [
      'Camera traversal: phase 1 pulls back 80% toward overview Z while lookAt pans old→new orb',
      'Camera traversal: phase 2 swoops back into 550u close-up tracking live orb position as rings rotate',
      'Duration 1.35s with easeInOutCubic on each half; orb throw animation continues independently',
    ],
    gitHash: '4d3a3c1',
    pages: ['Vistara'],
  },
  {
    version: '2.5',
    date: '2026-07-21',
    title: 'Vistara — Rings Restored',
    summary: 'Saturn rings disappeared in v2.3 due to sub-pixel point sizes (0.3px min) and the removal of the disc soft-fill in the fragment shader. Both restored with correct minimums.',
    changes: [
      'gl_PointSize minimum raised 0.3→1.0px — WebGL points below 1px are not rendered',
      'Disc fill restored in SATURN_FRAG (disc*0.55 + core*0.45) so each point has visible area',
      'Base particle aSize raised 0.3–1.2→0.8–1.8px so sizes are always ≥1px before distance scaling',
      'No HDR boost — rings remain halo-free at the new visible size',
    ],
    gitHash: '38db9ce',
    pages: ['Vistara'],
  },
  {
    version: '2.4',
    date: '2026-07-21',
    title: 'UX Fixes — One Console, No Phantom Cursor, Scrollable Panel',
    summary: 'Three UX regressions fixed: AcousticConsole removed from layout (SoundConsole is the single audio panel, already has ✕ close); custom cursor ring/dot hidden on touch/coarse-pointer devices; GlassPanel content area now scrolls on iOS via JS touch handlers.',
    changes: [
      'Removed AcousticConsole from cosmic layout — SoundConsole is the only audio panel',
      'Custom cursor (ring + dot + cursor:none) gated on window.matchMedia("(pointer:fine)") — invisible on mobile',
      'GlassPanel scrollable content div gets onTouchStart/onTouchMove JS handlers — bypasses global touch-action:none',
      'Panel Live Interface placeholder is now reachable by scrolling on iPhone',
    ],
    gitHash: 'c473821',
    pages: ['All pages', 'Vistara'],
  },
  {
    version: '2.3',
    date: '2026-07-21',
    title: 'Vistara — No Halos, Shared Color Cycle',
    summary: 'Disc/halo component stripped from both the core nebula and Saturn ring fragment shaders — only tight Gaussian point cores remain. Core now cycles the same red→blue→purple gradient as the rings. Bloom pass removed (nothing emits HDR anymore).',
    changes: [
      'SATURN_FRAG: removed disc * 0.72 term; pure exp(-r²×9) core only — no soft halo per particle',
      'SATURN_FRAG: removed HDR boost (col += sprk*vAlpha*0.9) — rings no longer trigger bloom',
      'CORE_FRAG: removed disc + azure static color; tight exp(-r²×9) core with same red→blue→purple cycle',
      'Core color slightly offset in cycle speed (0.04 vs 0.05) so core and rings are slightly phase-shifted',
      'EffectComposer + Bloom removed — was no-op once HDR outputs were eliminated, saves a GPU pass',
    ],
    gitHash: 'fdadd4b',
    pages: ['Vistara'],
  },
  {
    version: '2.2',
    date: '2026-07-21',
    title: 'Vistara — Core Nebula Particle Disc',
    summary: 'The central vortex billboard (a solid violet disc) is replaced with a 480-particle accretion disc in the XZ plane using differential rotation — inner particles orbit faster, azure-blue in the same particle language as the Saturn rings.',
    changes: [
      'Removed PlaneGeometry billboard vortex (was rendering as opaque violet/pink blob)',
      '480-particle disc at gyroscope origin, flat in XZ plane with ±3 unit Y scatter',
      'Differential rotation shader: inner r<10 orbits 3× faster than outer edge',
      'Density wave modulation (6 arms, 0.7 rad/s) gives natural spiral arm shaping',
      'Colour: electric azure (#47b8ff) → royal blue (#0a1fa6), matches orb palette',
      'Max point size 2px hard cap — stays coherent at all camera distances',
    ],
    gitHash: '640f918',
    pages: ['Vistara'],
  },
  {
    version: '2.1',
    date: '2026-07-21',
    title: 'Vistara — Orb Throw & Scaled Presence',
    summary: 'Clicking an orb now launches it physically toward the camera: a sin-bell position surge (180 units) + scale spike (2.5× rest) fires over 0.65 s, then settles to the larger focused size. Camera throw deepened from 72 to 160 units.',
    changes: [
      'Orb throw: on focus, group position lerps toward camera (parent-local direction) by up to 180 units',
      'Scale spike: orbSize×2.5 sin-bell over 0.65 s on focus, fast lerp (0.30) during peak',
      'Rest scale raised 0.15→0.30, focused scale raised 0.22→0.45 — orbs more prominent vs rings',
      'Camera throw: 72→160 units forward surge, duration 0.75→0.55 s, lerp 0.18→0.28',
    ],
    gitHash: '2c8a226',
    pages: ['Vistara'],
  },
  {
    version: '2.0',
    date: '2026-07-21',
    title: 'Vistara — Clean Orbs, Fine Stardust Rings',
    summary: 'Removed Fresnel rim halos that were rendering as visible circle outlines around orbs. Ring particles shrunk from 2.2–7px to 0.3–1.2px fine stardust with a hard 2px screen cap; HDR bloom boost reduced so ring sparkles glint rather than blob.',
    changes: [
      'Fresnel rim shader removed entirely — no more teal circle outlines on orbs',
      'Ring particles: 2.2–7px → 0.3–1.2px (fine stardust language)',
      'gl_PointSize hard cap 2.0px — prevents any particle blooming into a wide blob',
      'SATURN_VERT distance scale 580 → 300 — less screen-space magnification at close range',
      'HDR sparkle boost: sprk * vAlpha * 2.5 → 0.9 — tight star-point bloom, not halos',
    ],
    gitHash: 'a969787',
    pages: ['Vistara'],
  },
  {
    version: '1.9',
    date: '2026-07-21',
    title: 'Acoustic Consciousness — Living Sound Interface',
    summary: 'AcousticConsole is live on all cosmic pages: a full Web Audio synthesis engine with 8 procedural soundscapes, 12-band Neural EQ, spatial audio pad, 5 consciousness modes, plasma ring visualiser, BPM pulse, and spectrogram.',
    changes: [
      '8 soundscapes: Void Silence, Neural Drift, Crystal Resonance, Vortex Descent, Cathedral Bloom, Solar Ignition, Deep Current, Prāṇic Pulse',
      'All audio synthesized procedurally in Web Audio API — no files required',
      '12-band draggable Neural EQ with bezier curve SVG display',
      'Spatial audio XY pad with ripple visualiser',
      '5 consciousness modes (Prājña, Dhyāna, Akṣaya, Javā, Sañcāra) apply preset EQ curves',
      'Plasma ring visualiser + spectrogram + BPM pulse indicator',
      'Realm theme auto-detected from pathname: medha → purple, vistara → blue, shunya → violet',
      'Renders at bottom-right on all cosmic pages (zIndex 9300/9400)',
    ],
    gitHash: '54badca',
    pages: ['All pages'],
  },
  {
    version: '1.8',
    date: '2026-07-21',
    title: 'Vistara — Custom Cursor & Per-Gateway Panel Content',
    summary: 'Custom orbital cursor replaces the default pointer — a lagging ring expands on orb hover. Each gateway\'s side panel now shows three gateway-specific capability cards between the description and the Live Interface slot.',
    changes: [
      'Custom cursor: cursor:none on root, lagging ring (14% lerp/frame via rAF) + precision dot',
      'Ring: 32px idle → 52px on orb hover, spring cubic-bezier expansion, azure blue glow',
      'Dot: 4px exact-position indicator, brightens on hover',
      'Per-gateway feature cards: 3 "Core Capabilities" cards for all 8 gateways',
      'Cards styled with gateway accent colour: tinted background, numbered badge, upper-case title',
      'Feature cards appear between description and Live Interface placeholder in stagger step 4',
    ],
    gitHash: 'b80ad08',
    pages: ['Vistara'],
  },
  {
    version: '1.7',
    date: '2026-07-21',
    title: 'Vistara — 3D Starfield, Central Vortex & Fresnel Rim Glow',
    summary: 'Three depth upgrades: a 1500-star Three.js starfield replaces flat CSS dots for true camera parallax; a billboard vortex disc marks the gyroscope origin; each orb gains a Fresnel azure corona that brightens on focus.',
    changes: [
      '3D starfield: 1500 stars in sphere r=900–3600, blue-white/warm-yellow/lavender, sizeAttenuation shader',
      'Camera parallax: stars shift with zoom between overview and close-up',
      'Central vortex: billboard PlaneGeometry at (0,0,0) with swirl + concentric-pulse shader',
      'Vortex: violet→deep-blue gradient, bright white-violet core, always faces camera',
      'Fresnel rim: transparent sphere shell on every orb, electric azure glow at grazing angles',
      'Fresnel intensity: 0.18 idle → 0.52 hovered → 0.88 focused, lerped over 8 frames',
      'Fresnel radius tracks scaleRef×5.8 so the corona wraps the NanoOrb particle cloud',
    ],
    gitHash: '9342bff',
    pages: ['Vistara'],
  },
  {
    version: '1.6',
    date: '2026-07-21',
    title: 'Vistara — HDR Bloom on Ring Particle Cores',
    summary: 'Each Saturn ring particle now emits a tight star-point glow from its sparkle core. The void and orbs remain completely dark — bloom fires only on the HDR-boosted ring centres.',
    changes: [
      'SATURN_FRAG outputs HDR values at sparkle centres (col += sprk * vAlpha * 2.5)',
      'EffectComposer + Bloom with luminanceThreshold=0.85 — only ring cores qualify',
      'Disc area (sprk < 0.3) and NanoOrb particles stay below threshold — no halos',
      'radius=0.35, intensity=0.55, mipmapBlur — tight star-point, not screen-wide glow',
    ],
    gitHash: '32b3d66',
    pages: ['Vistara'],
  },
  {
    version: '1.5',
    date: '2026-07-21',
    title: 'Vistara — Stardust Meteors, Sound Icon & Universal Footer',
    summary: 'Shooting stars rebuilt as discrete stardust particle trails matching the Saturn ring language. Legal footer and copyright pill now hover-accessible on every page above all panels.',
    changes: [
      'Shooting stars: 2 max, 45-second cycle, staggered 22.5 s apart',
      'Trail rebuilt as 280 discrete motes with perpendicular scatter — stardust not a beam',
      'Per-particle size jitter and signed lateral scatter for organic ring-like density',
      'Hard 14px particle cap prevents any screen-filling blob at any camera distance',
      'ACOUSTIC shortcut button (top-left, below back) dispatches vyan:sound-toggle to SoundConsole',
      'SoundConsole gains external event listener for vyan:sound-toggle',
      'NebulaFooter enabled on all cosmic pages — removed /vyoma+/shunya route gate',
      'Footer z-index 8→9100, slab dialog 80→9200 — visible and clickable above all panels',
      'Version history: JS touch-scroll handlers replace broken CSS pan-y override',
      'Orbital rings: alpha 0.35→0.48, particles 2200→3000, size 1.5-5px→2.2-7px for low-brightness screens',
      'Ring width narrowed from 44% to 30% of radius — tighter, more defined band',
    ],
    gitHash: '156d53e',
    pages: ['Vistara', 'All pages'],
  },
  {
    version: '1.4',
    date: '2026-07-19',
    title: 'Vistara — Side-Sliding Panels & Live App Placeholders',
    summary: 'Orb panels now slide in from alternating left/right edges on desktop and sheet up from the bottom on mobile; a decorated live-app placeholder fills the interface slot until an app is ready.',
    changes: [
      'Even-indexed orbs open panel from the left edge; odd-indexed from the right',
      'Desktop panel: full-height sidebar (min(500px, 46vw)), slides in with spring ease',
      'Mobile panel: 88 vh bottom sheet with drag handle, slides up from bottom',
      'Backdrop blur (3px) replaces hard black overlay',
      'Inner-edge accent border glows in the gateway colour',
      'Top accent line (gradient) at panel crown, gateway tantra badge in header',
      'Scrollable content area with sticky footer buttons (Back + Enter)',
      'LiveAppPlaceholder: animated dot-grid, sweeping scan line, corner brackets, pulsing glow',
      'Placeholder shows when gateway.appUrl is unset; iframe mounts when set',
      'Closing animation accelerates back to the originating edge (not a generic fade)',
    ],
    gitHash: '0000000',
    pages: ['Vistara'],
  },
  {
    version: '1.3',
    date: '2026-07-19',
    title: 'Vistara — Overview Mode & OrbitControls',
    summary: 'Page now loads in a zoomable overview showing all 8 orbs; click any orb to fly into close-up, or tap Overview to return.',
    changes: [
      'Overview mode on load — camera at z=1300, full gyroscopic system visible',
      'OrbitControls in overview: scroll/pinch to zoom, drag to rotate the entire scene',
      'Click any orb from overview → smooth 0.9 s camera fly-in to close-up',
      'Overview button (bottom-right) in close-up → 1.4 s fly-out back to overview',
      'Orb labels hidden in overview for a clean birds-eye view; revealed on close-up',
      'Wheel/swipe traversal gated — only active in close-up mode',
      'Hint text updates: "Scroll · Pinch · Drag to explore · Tap an orb to enter" in overview',
      'Dot navigation bar hidden in overview; restored in close-up',
    ],
    gitHash: '4d32b1b',
    pages: ['Vistara'],
  },
  {
    version: '1.2',
    date: '2026-07-18',
    title: 'Site-wide Version History Panel',
    summary: 'Introduced the version badge and history panel visible across the entire website, so every release is documented and restorable.',
    changes: [
      'Version badge (bottom-left, site-wide) — click to open history panel',
      'Full version history panel with per-release change log and git hash',
      'Version registry in lib/versions.ts — updated with every release going forward',
    ],
    gitHash: 'fecf058',
    pages: ['All pages'],
  },
  {
    version: '1.1',
    date: '2026-07-18',
    title: 'Vistara — Phi Label Layout & Font Overhaul',
    summary: 'Label system redesigned: names stack vertically through the orb centre (φ), taglines anchor in CSS below the column in normal case.',
    changes: [
      'Phi (φ) layout — each name letter stacked as its own line, column bisects orb',
      'VYAN Shunyalekh bold italic (weight 700) for orb name labels',
      'Taglines in normal mixed case, horizontal, CSS-anchored below name column',
      'Font size auto-reduces only for names longer than 7 characters (min 18 px)',
      'Tagline fades to invisible on non-focused orbs (opacity transition 0.4s)',
      'Non-focused labels at opacity 0.28 to eliminate visual crowding',
      'Removed distanceFactor from Html labels — consistent font size across all orbit depths',
    ],
    gitHash: '8063059',
    pages: ['Vistara'],
  },
  {
    version: '1.0',
    date: '2026-07-17',
    title: 'Vistara Visual Foundation — Saturn Rings & Red Labels',
    summary: 'The visual milestone the client approved: Saturn-ring stardust gyroscopic rings, stark red labels, and the VYAN blue icon palette.',
    changes: [
      'Saturn-ring stardust particle systems replacing torus geometries',
      'Particle density waves tied to gyroscopic tilt via uTilt GLSL uniform',
      'Color-cycling particles: red → deep blue → dark purple loop via uTime',
      'Gyroscopic precession — diagonal secondary drift on all three rings',
      'Stark red labels (#ff4040) with triple-layer glow below each orb',
      'VYAN icons (Back, Send, Close) recoloured to deep royal blue / electric azure',
      'BackIcon in Vistara nav, Close + Send in GlassPanel and ComingSoon panels',
      'Live app iframe slot (appUrl?) added to GlassPanel for future embedding',
      'Medha consent form: sandhi@vyanlabs.com → admin@vyanlabs.com',
    ],
    gitHash: 'b14b812',
    pages: ['Vistara', 'Medhā'],
  },
  {
    version: '0.9',
    date: '2026-07-15',
    title: 'Vistara — Node Web, Star Trails & Glass Panel',
    summary: 'Full interactive experience: node web unfolds on panel open, phantom orbs, ShaderMaterial star trails, and camera throw.',
    changes: [
      'Node web unfolds outward when glass panel opens (sin-bell burst)',
      'Phantom NanoOrbs for secondary star-like presence between orbs',
      'ShaderMaterial star trails connecting orbs (TRAIL_VERT / TRAIL_FRAG GLSL)',
      'Camera throw toward focused orb on click, with lerp return',
      'Glass panel with CSS gradient shards replacing heavy clip-path animation',
      'Deep-blue orb colour palette, larger phantom orbs',
      'Nebula atmosphere and background starfield texture',
      'Coming Soon panel for unreleased gateway slots',
    ],
    gitHash: 'bacba59',
    pages: ['Vistara'],
  },
]

export const CURRENT_VERSION = '3.9.3'
