// ─── VYAN Website Version Registry ───────────────────────────────────────────
// Add a new entry at the TOP of SITE_VERSIONS for every meaningful release.
// Update CURRENT_VERSION to match.
// Tag the git commit: git tag v<version> <hash> && git push origin v<version>

export interface VersionEntry {
  version: string      // e.g. '1.2'
  date: string         // YYYY-MM-DD
  title: string        // short release name
  summary: string      // one or two sentences
  changes: string[]    // bullet list of what changed
  gitHash: string      // first 7 chars of commit hash
  pages: string[]      // which pages / systems were touched
}

export const CURRENT_VERSION = '3.4'

export const SITE_VERSIONS: VersionEntry[] = [
  {
    version: '3.4',
    date: '2026-07-23',
    title: 'Vistara — Each Orb Owns Its Ring (Depth & Proportion)',
    summary: 'Each of 9 orbs now sits at a unique fixed 3D world position with its own local ring wrapping it — no more shared-origin stacking. Clear depth, distance and proportion visible from the overview.',
    changes: [
      '9 orbs at distinct 3D positions: Z spread +250 to -260 (front-to-back depth), X: ±220, Y: ±160',
      'Ring wraps its own orb locally (ringA 44-68, ringB 34-52 proportional to orb size) — no overlap with other rings',
      'Ring group rotates/gyrates around the orb; orb stays fixed at its world position',
      'Nearest orb appears largest in overview, farthest appears smallest — depth perception restored',
      'Camera flies to 350 units in front of each orb for close-up; 360° gyroscopic arc traversal between orbs',
      'Overview camera range 750-1200 units (portrait wider to fit ±220 X spread)',
      'Per-particle count 4000→1500 (proportional to smaller ring circumference)',
    ],
    gitHash: 'bc6a005',
    pages: ['Vistara'],
  },
  {
    version: '3.3',
    date: '2026-07-23',
    title: 'Vistara — Nano-Particle String Rings (No Donut)',
    summary: 'Rings are now true sparse strings of individual nano-particles visible from any angle — eliminated the solid-donut artifact caused by 9 rings × AdditiveBlending stacking at origin.',
    changes: [
      'Particle count per ring reduced 11000→4000 — visible gaps between beads, genuine nano-string look',
      'Particles placed exactly on the ellipse curve (zero radial spread, zero Y jitter) — ring appears as a thin line of beads from any viewing angle',
      'Per-particle alpha ×0.22 to compensate for 9 rings additively stacking at the same origin — prevents saturation into a solid donut while keeping crystal colour bands vivid',
      'Wave displacement is the sole source of 3D motion — string physically ripples without thickening',
    ],
    gitHash: '0e0d0db',
    pages: ['Vistara'],
  },
  {
    version: '3.1',
    date: '2026-07-23',
    title: 'Vistara — Thin Rings, Traveling Arc Wave, Crystal Diffraction',
    summary: 'Rings thinned 3.5×, a sharp arc of light orbits each ring at unique speeds, and prismatic crystal diffraction gives every particle a distinct hard-edged colour facet.',
    changes: [
      'Ring width reduced from 11% to 3.2% of major axis — crisp thin band, future-proof for more orbs',
      'Traveling arc wave: sharp-fronted crescent sweeps each ring in XZ plane via fract()+step()',
      '9 unique wave speeds (±0.06–0.24) and crest widths — some clockwise, some counter-clockwise',
      'Crystal diffraction: per-particle vPhase offsets colour cycle, quantised into 12 hard bands',
      'Zero glow, zero white, zero blur — pure prismatic colour-faceting on hard disc particles',
      'Orb spread fix: 9 localAngles at π/2 + i×(2π/9) so no clustering on page load',
    ],
    gitHash: '41757e7',
    pages: ['Vistara'],
  },
  {
    version: '3.0',
    date: '2026-07-22',
    title: 'Vistara — 9 Orbs, Per-Orb Rings, Stardust Web, Cinematic Camera',
    summary: 'Nine individual gyroscopic rings (one per orb, each a different ellipse), Saṅgraha as the 9th orb, flowing web stardust replacing line segments, cinematic camera arc (2.5s), and Overview button finally above the footer.',
    changes: [
      'Per-orb rings: 9 individual elliptical gyroscopic rings replacing 3 shared rings',
      'Each ring: distinct ellipse shape, unique color gradient offset, independent spin axis + drift',
      'Saṅgraha added as 9th orb (purple, Z-spin ring, 225-unit circle)',
      'Web stardust: flowing particles trace edge paths (opacity 0.55, traveling wave shader)',
      'LineSegments web opacity reduced 0.42→0.06; stardust carries the visual',
      'Camera traverse duration 1.35s→2.5s; pull-back to 1.05× overview Z for cinematic arc',
      'Overview button extracted from z-index:100 stacking context — now truly above footer',
      'uColorOffset uniform per ring: each ring starts at a different point in red→blue→purple cycle',
    ],
    gitHash: 'eb6dd73',
    pages: ['Vistara'],
  },
  {
    version: '2.9',
    date: '2026-07-22',
    title: 'Vistara — Panel UX + Icons + Sound + Rings + Header',
    summary: 'Five UX fixes: panel touch-scroll, clickable version/overview icons, sound console visible, Saturn-like ring particles, stark-red name + shimmer tagline in panel header.',
    changes: [
      'Panel scroll: pointer/touch stopPropagation on slab + preventDefault on scroll div',
      'Version badge and Overview button z-index raised to 9200 (above NebulaFooter 9100)',
      'SoundConsole z-index raised 25→8500 — panel now opens above canvas',
      'Saturn rings: 14000 particles/ring, 0.4–1.1px, hard step() disc (zero blur)',
      'Panel header orb name: stark red #e80010',
      'Panel tagline: deep-blue→purple gradient shimmer, alternating L↔R per orb',
    ],
    gitHash: 'd8490b5',
    pages: ['Vistara', 'All pages'],
  },
  {
    version: '2.8',
    date: '2026-07-22',
    title: 'Vistara — v1.9 Ring Shader Restored',
    summary: 'Stardust ring particles restored to v1.9 proportional sizing (2.2–7px, aSize-relative min/max). Proportional formula prevents the uniform-blob look caused by fixed pixel clamps.',
    changes: [
      'aSize 2.2–7px (v1.9 range restored)',
      'gl_PointSize: clamp(aSize*580/dist, aSize*1.1, aSize*2.5) — proportional min/max',
      'Fragment: disc smoothstep(0.05→0.88), disc*0.72 + sprk*0.55',
      'vAlpha density*(0.65 + uTilt*1.4) — brighter than v1.9 to compensate for no bloom',
      '5000 particles per ring',
    ],
    gitHash: 'e3eb8c0',
    pages: ['Vistara'],
  },
  {
    version: '2.7',
    date: '2026-07-22',
    title: 'Vistara — Rings Actually Visible',
    summary: 'Saturn stardust rings were invisible after glow-removal over-correction — 1px particles at 12% alpha. Rebuilt with 7000 particles per ring at 2.5–5px, 70% base alpha, and brighter fragment output.',
    changes: [
      'Particle count 3000→7000 per ring for continuous visible arc coverage',
      'Base aSize 0.8–1.8px→2.5–5px; gl_PointSize max 2.5→9px',
      'vAlpha base 0.48→0.70 — rings are always bright, density wave modulates ±15%',
      'Fragment output col*1.2 — clean stardust, no bloom, no halo',
    ],
    gitHash: '106d9cc',
    pages: ['Vistara'],
  },
  {
    version: '2.6',
    date: '2026-07-22',
    title: 'Vistara — Camera Arc Traversal',
    summary: 'When switching between focused orbs, the camera now arcs through the gyroscope scene: pulling back toward overview distance while panning to the new orb, then swooping back into close-up.',
    changes: [
      'Camera traversal: phase 1 pulls back 80% toward overview Z while lookAt pans old→new orb',
      'Camera traversal: phase 2 swoops back into 550u close-up tracking live orb position as rings rotate',
      'Duration 1.35s with easeInOutCubic on each half; orb throw animation continues independently',
    ],
    gitHash: '4d3a3c1',
    pages: ['Vistara'],
  },
  {
    version: '2.5',
    date: '2026-07-21',
    title: 'Vistara — Rings Restored',
    summary: 'Saturn rings disappeared in v2.3 due to sub-pixel point sizes (0.3px min) and the removal of the disc soft-fill in the fragment shader. Both restored with correct minimums.',
    changes: [
      'gl_PointSize minimum raised 0.3→1.0px — WebGL points below 1px are not rendered',
      'Disc fill restored in SATURN_FRAG (disc*0.55 + core*0.45) so each point has visible area',
      'Base particle aSize raised 0.3–1.2→0.8–1.8px so sizes are always ≥1px before distance scaling',
      'No HDR boost — rings remain halo-free at the new visible size',
    ],
    gitHash: '38db9ce',
    pages: ['Vistara'],
  },
  {
    version: '2.4',
    date: '2026-07-21',
    title: 'UX Fixes — One Console, No Phantom Cursor, Scrollable Panel',
    summary: 'Three UX regressions fixed: AcousticConsole removed from layout (SoundConsole is the single audio panel, already has ✕ close); custom cursor ring/dot hidden on touch/coarse-pointer devices; GlassPanel content area now scrolls on iOS via JS touch handlers.',
    changes: [
      'Removed AcousticConsole from cosmic layout — SoundConsole is the only audio panel',
      'Custom cursor (ring + dot + cursor:none) gated on window.matchMedia("(pointer:fine)") — invisible on mobile',
      'GlassPanel scrollable content div gets onTouchStart/onTouchMove JS handlers — bypasses global touch-action:none',
      'Panel Live Interface placeholder is now reachable by scrolling on iPhone',
    ],
    gitHash: 'c473821',
    pages: ['All pages', 'Vistara'],
  },
  {
    version: '2.3',
    date: '2026-07-21',
    title: 'Vistara — No Halos, Shared Color Cycle',
    summary: 'Disc/halo component stripped from both the core nebula and Saturn ring fragment shaders — only tight Gaussian point cores remain. Core now cycles the same red→blue→purple gradient as the rings. Bloom pass removed (nothing emits HDR anymore).',
    changes: [
      'SATURN_FRAG: removed disc * 0.72 term; pure exp(-r²×9) core only — no soft halo per particle',
      'SATURN_FRAG: removed HDR boost (col += sprk*vAlpha*0.9) — rings no longer trigger bloom',
      'CORE_FRAG: removed disc + azure static color; tight exp(-r²×9) core with same red→blue→purple cycle',
      'Core color slightly offset in cycle speed (0.04 vs 0.05) so core and rings are slightly phase-shifted',
      'EffectComposer + Bloom removed — was no-op once HDR outputs were eliminated, saves a GPU pass',
    ],
    gitHash: 'fdadd4b',
    pages: ['Vistara'],
  },
  {
    version: '2.2',
    date: '2026-07-21',
    title: 'Vistara — Core Nebula Particle Disc',
    summary: 'The central vortex billboard (a solid violet disc) is replaced with a 480-particle accretion disc in the XZ plane using differential rotation — inner particles orbit faster, azure-blue in the same particle language as the Saturn rings.',
    changes: [
      'Removed PlaneGeometry billboard vortex (was rendering as opaque violet/pink blob)',
      '480-particle disc at gyroscope origin, flat in XZ plane with ±3 unit Y scatter',
      'Differential rotation shader: inner r<10 orbits 3× faster than outer edge',
      'Density wave modulation (6 arms, 0.7 rad/s) gives natural spiral arm shaping',
      'Colour: electric azure (#47b8ff) → royal blue (#0a1fa6), matches orb palette',
      'Max point size 2px hard cap — stays coherent at all camera distances',
    ],
    gitHash: '640f918',
    pages: ['Vistara'],
  },
  {
    version: '2.1',
    date: '2026-07-21',
    title: 'Vistara — Orb Throw & Scaled Presence',
    summary: 'Clicking an orb now launches it physically toward the camera: a sin-bell position surge (180 units) + scale spike (2.5× rest) fires over 0.65 s, then settles to the larger focused size. Camera throw deepened from 72 to 160 units.',
    changes: [
      'Orb throw: on focus, group position lerps toward camera (parent-local direction) by up to 180 units',
      'Scale spike: orbSize×2.5 sin-bell over 0.65 s on focus, fast lerp (0.30) during peak',
      'Rest scale raised 0.15→0.30, focused scale raised 0.22→0.45 — orbs more prominent vs rings',
      'Camera throw: 72→160 units forward surge, duration 0.75→0.55 s, lerp 0.18→0.28',
    ],
    gitHash: '2c8a226',
    pages: ['Vistara'],
  },
  {
    version: '2.0',
    date: '2026-07-21',
    title: 'Vistara — Clean Orbs, Fine Stardust Rings',
    summary: 'Removed Fresnel rim halos that were rendering as visible circle outlines around orbs. Ring particles shrunk from 2.2–7px to 0.3–1.2px fine stardust with a hard 2px screen cap; HDR bloom boost reduced so ring sparkles glint rather than blob.',
    changes: [
      'Fresnel rim shader removed entirely — no more teal circle outlines on orbs',
      'Ring particles: 2.2–7px → 0.3–1.2px (fine stardust language)',
      'gl_PointSize hard cap 2.0px — prevents any particle blooming into a wide blob',
      'SATURN_VERT distance scale 580 → 300 — less screen-space magnification at close range',
      'HDR sparkle boost: sprk * vAlpha * 2.5 → 0.9 — tight star-point bloom, not halos',
    ],
    gitHash: 'a969787',
    pages: ['Vistara'],
  },
  {
    version: '1.9',
    date: '2026-07-21',
    title: 'Acoustic Consciousness — Living Sound Interface',
    summary: 'AcousticConsole is live on all cosmic pages: a full Web Audio synthesis engine with 8 procedural soundscapes, 12-band Neural EQ, spatial audio pad, 5 consciousness modes, plasma ring visualiser, BPM pulse, and spectrogram.',
    changes: [
      '8 soundscapes: Void Silence, Neural Drift, Crystal Resonance, Vortex Descent, Cathedral Bloom, Solar Ignition, Deep Current, Prāṇic Pulse',
      'All audio synthesized procedurally in Web Audio API — no files required',
      '12-band draggable Neural EQ with bezier curve SVG display',
      'Spatial audio XY pad with ripple visualiser',
      '5 consciousness modes (Prājña, Dhyāna, Akṣaya, Javā, Sañcāra) apply preset EQ curves',
      'Plasma ring visualiser + spectrogram + BPM pulse indicator',
      'Realm theme auto-detected from pathname: medha → purple, vistara → blue, shunya → violet',
      'Renders at bottom-right on all cosmic pages (zIndex 9300/9400)',
    ],
    gitHash: '54badca',
    pages: ['All pages'],
  },
  {
    version: '1.8',
    date: '2026-07-21',
    title: 'Vistara — Custom Cursor & Per-Gateway Panel Content',
    summary: 'Custom orbital cursor replaces the default pointer — a lagging ring expands on orb hover. Each gateway\'s side panel now shows three gateway-specific capability cards between the description and the Live Interface slot.',
    changes: [
      'Custom cursor: cursor:none on root, lagging ring (14% lerp/frame via rAF) + precision dot',
      'Ring: 32px idle → 52px on orb hover, spring cubic-bezier expansion, azure blue glow',
      'Dot: 4px exact-position indicator, brightens on hover',
      'Per-gateway feature cards: 3 "Core Capabilities" cards for all 8 gateways',
      'Cards styled with gateway accent colour: tinted background, numbered badge, upper-case title',
      'Feature cards appear between description and Live Interface placeholder in stagger step 4',
    ],
    gitHash: 'b80ad08',
    pages: ['Vistara'],
  },
  {
    version: '1.7',
    date: '2026-07-21',
    title: 'Vistara — 3D Starfield, Central Vortex & Fresnel Rim Glow',
    summary: 'Three depth upgrades: a 1500-star Three.js starfield replaces flat CSS dots for true camera parallax; a billboard vortex disc marks the gyroscope origin; each orb gains a Fresnel azure corona that brightens on focus.',
    changes: [
      '3D starfield: 1500 stars in sphere r=900–3600, blue-white/warm-yellow/lavender, sizeAttenuation shader',
      'Camera parallax: stars shift with zoom between overview and close-up',
      'Central vortex: billboard PlaneGeometry at (0,0,0) with swirl + concentric-pulse shader',
      'Vortex: violet→deep-blue gradient, bright white-violet core, always faces camera',
      'Fresnel rim: transparent sphere shell on every orb, electric azure glow at grazing angles',
      'Fresnel intensity: 0.18 idle → 0.52 hovered → 0.88 focused, lerped over 8 frames',
      'Fresnel radius tracks scaleRef×5.8 so the corona wraps the NanoOrb particle cloud',
    ],
    gitHash: '9342bff',
    pages: ['Vistara'],
  },
  {
    version: '1.6',
    date: '2026-07-21',
    title: 'Vistara — HDR Bloom on Ring Particle Cores',
    summary: 'Each Saturn ring particle now emits a tight star-point glow from its sparkle core. The void and orbs remain completely dark — bloom fires only on the HDR-boosted ring centres.',
    changes: [
      'SATURN_FRAG outputs HDR values at sparkle centres (col += sprk * vAlpha * 2.5)',
      'EffectComposer + Bloom with luminanceThreshold=0.85 — only ring cores qualify',
      'Disc area (sprk < 0.3) and NanoOrb particles stay below threshold — no halos',
      'radius=0.35, intensity=0.55, mipmapBlur — tight star-point, not screen-wide glow',
    ],
    gitHash: '32b3d66',
    pages: ['Vistara'],
  },
  {
    version: '1.5',
    date: '2026-07-21',
    title: 'Vistara — Stardust Meteors, Sound Icon & Universal Footer',
    summary: 'Shooting stars rebuilt as discrete stardust particle trails matching the Saturn ring language. Legal footer and copyright pill now hover-accessible on every page above all panels.',
    changes: [
      'Shooting stars: 2 max, 45-second cycle, staggered 22.5 s apart',
      'Trail rebuilt as 280 discrete motes with perpendicular scatter — stardust not a beam',
      'Per-particle size jitter and signed lateral scatter for organic ring-like density',
      'Hard 14px particle cap prevents any screen-filling blob at any camera distance',
      'ACOUSTIC shortcut button (top-left, below back) dispatches vyan:sound-toggle to SoundConsole',
      'SoundConsole gains external event listener for vyan:sound-toggle',
      'NebulaFooter enabled on all cosmic pages — removed /vyoma+/shunya route gate',
      'Footer z-index 8→9100, slab dialog 80→9200 — visible and clickable above all panels',
      'Version history: JS touch-scroll handlers replace broken CSS pan-y override',
      'Orbital rings: alpha 0.35→0.48, particles 2200→3000, size 1.5-5px→2.2-7px for low-brightness screens',
      'Ring width narrowed from 44% to 30% of radius — tighter, more defined band',
    ],
    gitHash: '156d53e',
    pages: ['Vistara', 'All pages'],
  },
  {
    version: '1.4',
    date: '2026-07-19',
    title: 'Vistara — Side-Sliding Panels & Live App Placeholders',
    summary: 'Orb panels now slide in from alternating left/right edges on desktop and sheet up from the bottom on mobile; a decorated live-app placeholder fills the interface slot until an app is ready.',
    changes: [
      'Even-indexed orbs open panel from the left edge; odd-indexed from the right',
      'Desktop panel: full-height sidebar (min(500px, 46vw)), slides in with spring ease',
      'Mobile panel: 88 vh bottom sheet with drag handle, slides up from bottom',
      'Backdrop blur (3px) replaces hard black overlay',
      'Inner-edge accent border glows in the gateway colour',
      'Top accent line (gradient) at panel crown, gateway tantra badge in header',
      'Scrollable content area with sticky footer buttons (Back + Enter)',
      'LiveAppPlaceholder: animated dot-grid, sweeping scan line, corner brackets, pulsing glow',
      'Placeholder shows when gateway.appUrl is unset; iframe mounts when set',
      'Closing animation accelerates back to the originating edge (not a generic fade)',
    ],
    gitHash: '0000000',
    pages: ['Vistara'],
  },
  {
    version: '1.3',
    date: '2026-07-19',
    title: 'Vistara — Overview Mode & OrbitControls',
    summary: 'Page now loads in a zoomable overview showing all 8 orbs; click any orb to fly into close-up, or tap Overview to return.',
    changes: [
      'Overview mode on load — camera at z=1300, full gyroscopic system visible',
      'OrbitControls in overview: scroll/pinch to zoom, drag to rotate the entire scene',
      'Click any orb from overview → smooth 0.9 s camera fly-in to close-up',
      'Overview button (bottom-right) in close-up → 1.4 s fly-out back to overview',
      'Orb labels hidden in overview for a clean birds-eye view; revealed on close-up',
      'Wheel/swipe traversal gated — only active in close-up mode',
      'Hint text updates: "Scroll · Pinch · Drag to explore · Tap an orb to enter" in overview',
      'Dot navigation bar hidden in overview; restored in close-up',
    ],
    gitHash: '4d32b1b',
    pages: ['Vistara'],
  },
  {
    version: '1.2',
    date: '2026-07-18',
    title: 'Site-wide Version History Panel',
    summary: 'Introduced the version badge and history panel visible across the entire website, so every release is documented and restorable.',
    changes: [
      'Version badge (bottom-left, site-wide) — click to open history panel',
      'Full version history panel with per-release change log and git hash',
      'Version registry in lib/versions.ts — updated with every release going forward',
    ],
    gitHash: 'fecf058',
    pages: ['All pages'],
  },
  {
    version: '1.1',
    date: '2026-07-18',
    title: 'Vistara — Phi Label Layout & Font Overhaul',
    summary: 'Label system redesigned: names stack vertically through the orb centre (φ), taglines anchor in CSS below the column in normal case.',
    changes: [
      'Phi (φ) layout — each name letter stacked as its own line, column bisects orb',
      'VYAN Shunyalekh bold italic (weight 700) for orb name labels',
      'Taglines in normal mixed case, horizontal, CSS-anchored below name column',
      'Font size auto-reduces only for names longer than 7 characters (min 18 px)',
      'Tagline fades to invisible on non-focused orbs (opacity transition 0.4s)',
      'Non-focused labels at opacity 0.28 to eliminate visual crowding',
      'Removed distanceFactor from Html labels — consistent font size across all orbit depths',
    ],
    gitHash: '8063059',
    pages: ['Vistara'],
  },
  {
    version: '1.0',
    date: '2026-07-17',
    title: 'Vistara Visual Foundation — Saturn Rings & Red Labels',
    summary: 'The visual milestone the client approved: Saturn-ring stardust gyroscopic rings, stark red labels, and the VYAN blue icon palette.',
    changes: [
      'Saturn-ring stardust particle systems replacing torus geometries',
      'Particle density waves tied to gyroscopic tilt via uTilt GLSL uniform',
      'Color-cycling particles: red → deep blue → dark purple loop via uTime',
      'Gyroscopic precession — diagonal secondary drift on all three rings',
      'Stark red labels (#ff4040) with triple-layer glow below each orb',
      'VYAN icons (Back, Send, Close) recoloured to deep royal blue / electric azure',
      'BackIcon in Vistara nav, Close + Send in GlassPanel and ComingSoon panels',
      'Live app iframe slot (appUrl?) added to GlassPanel for future embedding',
      'Medha consent form: sandhi@vyanlabs.com → admin@vyanlabs.com',
    ],
    gitHash: 'b14b812',
    pages: ['Vistara', 'Medhā'],
  },
  {
    version: '0.9',
    date: '2026-07-15',
    title: 'Vistara — Node Web, Star Trails & Glass Panel',
    summary: 'Full interactive experience: node web unfolds on panel open, phantom orbs, ShaderMaterial star trails, and camera throw.',
    changes: [
      'Node web unfolds outward when glass panel opens (sin-bell burst)',
      'Phantom NanoOrbs for secondary star-like presence between orbs',
      'ShaderMaterial star trails connecting orbs (TRAIL_VERT / TRAIL_FRAG GLSL)',
      'Camera throw toward focused orb on click, with lerp return',
      'Glass panel with CSS gradient shards replacing heavy clip-path animation',
      'Deep-blue orb colour palette, larger phantom orbs',
      'Nebula atmosphere and background starfield texture',
      'Coming Soon panel for unreleased gateway slots',
    ],
    gitHash: 'bacba59',
    pages: ['Vistara'],
  },
]

